### ISSUE TITLE
Update project wiki

### ISSUE THREAD

**Issue by SagarMishra** [codeforgso/GoVote#43]
should include:
-MVP design and some proposed features
-build instructions
-Resources (PMs, Contributors, Community Stakeholders)
-Community Requirements

**Comment by ElizabethBeck** [comment]
Hi Sagar, This is ellie from the meeting today. I have a little bit of experience with github, design, and how the civic and technical aspects of projects come together. What can I do, if anything, to help of this issue or any other issue you might find me more suited to? Let me know! I am here to contribute.

**Comment by SagarMishra** [comment]
i created an version 1 of the wiki page if you want to check it out. i probably need to flesh out the MVP in more detail for the technical team.

**Comment by zenlex** [comment]
I think this is where we need to start now - redefine the MVP in the context of the 2020 election and update the issue backlog/project board accordingly. A lot of stuff needs to be abandoned or tabled at this point to make it viable for this year and since this already exists, refining it and the related backlog seems like a good way to get everyone on the same page and bring any additional interested help up to speed quickly.

**Comment by tleisman** [comment]
Updated the wiki with 2020 MVP.
